### ISSUE TITLE
No promise support

### ISSUE THREAD

**Issue by javacoolme** [FuturisticCake/phin#2]
Use promises!

**Comment by FuturisticCake** [comment]
Aye! **I see you've currently got your own fork of the project.** Feel free to add promise functionality to your own code or build a higher-level wrapper for phin which implements promises. I'll soon consider implementing it over here after fully finishing testing of version 1.0.4 and adding a few other features.

**Comment by bdsomer** [comment]
Fixed in https://github.com/ethanent/phin/pull/5, if anyone was wondering.
